name: Job Vacancy Manager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
      - name: Build Project
        run: mvn clean install
      - name: Login Docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t caiquebrener/job_vacancy_manager .
      - name: Publish Image
        run: docker push caiquebrener/job_vacancy_manager